spring:
  config:
    name: practypdb
  datasource:
    url: jdbc:postgresql://localhost:5432/4db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: practyp-async-

server:
  port: 8888
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 1800s

jwt:
  secret: mySecretKeyForJWTTokenGenerationInSpringBootApplicationWithMinimum256BitsLengthForHS256Algorithm
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.mpt.practyp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE